### PR TITLE
Webdev

### PR DESCRIPTION
**Pull request by cemyld**
Adds phageAPI django project with initialized models.

### CODE REVIEW

**Comment by QuLogic** [comment]
You might want to rebase again (interactively), edit the first commit, and delete the `.DS_Store` that was added in this line.

**Comment by mbonsma** [comment]
@cemyld, somehow you ended up with your gitignore commits and that commit from me - maybe another rebase?

**Comment by cemyld** [comment]
Alright, it looks fine now. The proposed commits should only alter the api files.

**Comment by mbonsma** [comment]
Ok I merged it - hopefully the conflicts have been dealt with appropriately. 

At this point if you don't have any new changes, it might a good time to start fresh with your local copy exactly the same as the upstream version.

**Pull request merged**
