### PR TITLE
changed uppercase names to lower case on some python files

### PR DESCRIPTION
**Pull request by wgma00**
PR for #165

### CODE REVIEW

**Comment by djmitche** [comment]
There are some mentions of `BLAST_loop.py` and `PFAM_db.py` in the README and in those files that should probably be updated with the new capitalization, too.

**Comment by mbonsma** [comment]
Awesome, thanks @wgma00! :clap: 

Fixes #165

**Comment by mbonsma** [comment]
@djmitche - yeah we should probably also change the spellings there.

**Comment by wgma00** [comment]
I've updated the references in a new commit. grep doesn't show any other references to the files.

**Pull request merged**
